[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "generate-acp-test11"
version = "0.1.0"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "jupyter",
    "adjustText"
]
authors = [
  { name="Frédéric Gainza", email="kopatiktak@gmail.com" },
]
description = "Génréation des données et des graphiques d\'une ACP"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
        "Framework :: Jupyter",
        "Topic :: Scientific/Engineering :: Visualization"
]

[project.urls]
"Homepage" = "https://github.com/FredGainza/generateACP"
